const STORAGE_KEY = "bm-defense-coach-v1";

const categoryLabels = {
  daily: "日常交流",
  polite: "礼貌缓冲",
  meeting: "导师沟通",
  opening: "答辩开场",
  structure: "报告结构",
  research: "研究内容",
  qa: "答辩问答",
  closing: "收尾感谢",
  vocab: "学术词汇",
};

const resources = [
  {
    id: "futurelearn",
    title: "Universiti Malaya / FutureLearn 入门课程",
    type: "主线课程",
    url: "https://www.classcentral.com/course/learn-bahasa-melayu-introduction-to-the-malay-language-95194",
    value: "三周入门，适合第1-3周打底：发音、问候、自我介绍、数字、时间。",
    use: "每周看2-3次，每次只抓能用于老师交流的句型，不追求完整学完。",
  },
  {
    id: "grovo",
    title: "GroVo Malay",
    type: "手机碎片练习",
    url: "https://grovo.org/grovo-malay/",
    value: "免费、无广告，适合用大量例句建立语感。",
    use: "作为补充资源使用，不再把它作为每日发音训练任务。",
  },
  {
    id: "llingo",
    title: "L-Lingo Malay Free Lessons",
    type: "真人发音",
    url: "https://l-lingo.com/free-lessons/en/learn-malay/",
    value: "有基础问候和常用短句的真人发音，适合校正开口时的节奏。",
    use: "只在需要确认真实发音时打开，不依赖浏览器朗读。",
  },
  {
    id: "dbp",
    title: "Kamus DBP",
    type: "官方词典",
    url: "https://kamus.dbp.gov.my/",
    value: "马来西亚官方语言机构DBP的在线词典，适合查正式词语和拼写。",
    use: "论文关键词、答辩标题、正式表达先在这里查；不确定就保留英文术语。",
  },
  {
    id: "hilokal",
    title: "Hilokal Malay",
    type: "口语实战",
    url: "https://www.hilokal.com/en/learn/malay",
    value: "有免费马来语学习和语音交流环境，适合练胆量。",
    use: "第4周后再用，目标是练“听不懂时如何请求重复”和自我介绍。",
  },
  {
    id: "wikibooks",
    title: "Wikibooks Malay",
    type: "开放教材",
    url: "https://en.wikibooks.org/wiki/Malay",
    value: "开放式语法和基础教材，适合查句子结构。",
    use: "只在遇到语法困惑时查，不把它当主课本。",
  },
  {
    id: "ankidroid",
    title: "AnkiDroid",
    type: "开源复习工具",
    url: "https://github.com/ankidroid/Anki-Android",
    value: "开源间隔重复工具。这个平台也能导出Anki可导入的TSV卡片。",
    use: "如果你想在手机上背卡片，就从“复习”页导出，再导入AnkiDroid。",
  },
  {
    id: "rtranslator",
    title: "RTranslator",
    type: "开源翻译备用",
    url: "https://github.com/niedev/RTranslator",
    value: "开源安卓实时翻译工具，可作为临时救场，不建议替代学习。",
    use: "答辩当天只作为备用，不要依赖它完成正式表达。",
  },
  {
    id: "frequency",
    title: "Wiktionary Malay Frequency Lists",
    type: "词频参考",
    url: "https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/Malay",
    value: "用于判断高频词优先级。平台句库已经优先选了答辩高频表达。",
    use: "你需要扩充生活词汇时再查，答辩阶段不用大规模背词表。",
  },
];

const phrases = [
  { id: "p001", day: 1, category: "daily", ms: "Selamat pagi, Profesor.", zh: "教授，早上好。", note: "正式场合稳妥。也可把Profesor换成Dr." },
  { id: "p002", day: 1, category: "daily", ms: "Apa khabar, Dr.?", zh: "老师，您好吗？", note: "日常寒暄。回答可用 Saya baik, terima kasih." },
  { id: "p003", day: 1, category: "daily", ms: "Saya baik, terima kasih.", zh: "我很好，谢谢。", note: "最常用回答之一。" },
  { id: "p004", day: 2, category: "daily", ms: "Nama saya ialah ___.", zh: "我的名字是___。", note: "自我介绍固定句。" },
  { id: "p005", day: 2, category: "daily", ms: "Saya pelajar tahun akhir.", zh: "我是最后一年学生。", note: "毕业答辩前常用。" },
  { id: "p006", day: 2, category: "daily", ms: "Saya sedang belajar bahasa Melayu.", zh: "我正在学习马来语。", note: "自然解释自己的水平。" },
  { id: "p007", day: 3, category: "polite", ms: "Maaf, bahasa Melayu saya masih terhad.", zh: "抱歉，我的马来语还有限。", note: "为自己争取理解空间。" },
  { id: "p008", day: 3, category: "polite", ms: "Boleh saya cuba jawab dalam bahasa Melayu dahulu?", zh: "我可以先试着用马来语回答吗？", note: "答辩时很实用，也显得主动。" },
  { id: "p009", day: 3, category: "polite", ms: "Jika perlu, saya akan sambung dalam bahasa Inggeris.", zh: "如果需要，我会接着用英语说明。", note: "给自己留切换语言的余地。" },
  { id: "p010", day: 4, category: "polite", ms: "Boleh Prof. ulang sekali lagi?", zh: "教授可以再重复一遍吗？", note: "简洁自然。" },
  { id: "p011", day: 4, category: "polite", ms: "Boleh Prof. bercakap sedikit perlahan?", zh: "教授可以说慢一点吗？", note: "听不清时使用。" },
  { id: "p012", day: 4, category: "polite", ms: "Saya kurang faham bahagian terakhir.", zh: "我不太明白最后一部分。", note: "比直接说听不懂更具体。" },
  { id: "p013", day: 5, category: "meeting", ms: "Maaf mengganggu, saya ingin bertanya tentang draf saya.", zh: "抱歉打扰，我想问一下我的草稿。", note: "给导师发消息可用。" },
  { id: "p014", day: 5, category: "meeting", ms: "Boleh saya tetapkan temu janji dengan Prof. minggu ini?", zh: "我可以和教授约这周的见面时间吗？", note: "预约见面。" },
  { id: "p015", day: 5, category: "meeting", ms: "Adakah Prof. lapang pada hari Isnin?", zh: "教授星期一有空吗？", note: "把Isnin替换成具体日期。" },
  { id: "p016", day: 6, category: "meeting", ms: "Saya telah menghantar fail melalui e-mel.", zh: "我已经通过邮件发送文件。", note: "汇报文件状态。" },
  { id: "p017", day: 6, category: "meeting", ms: "Boleh saya sahkan masa pertemuan kita?", zh: "我可以确认一下我们的见面时间吗？", note: "避免误会。" },
  { id: "p018", day: 6, category: "meeting", ms: "Terima kasih atas bimbingan Prof.", zh: "谢谢教授的指导。", note: "邮件或见面结束都可用。" },
  { id: "p019", day: 7, category: "meeting", ms: "Saya akan membuat pembetulan secepat mungkin.", zh: "我会尽快修改。", note: "收到反馈后的回应。" },
  { id: "p020", day: 7, category: "meeting", ms: "Saya ingin mendapatkan maklum balas tentang bahagian ini.", zh: "我想获得关于这一部分的反馈。", note: "请老师具体看某一段。" },
  { id: "p021", day: 8, category: "opening", ms: "Assalamualaikum dan selamat pagi kepada semua.", zh: "各位早上好。", note: "如不确定场合，可只用 Selamat pagi kepada semua." },
  { id: "p022", day: 8, category: "opening", ms: "Terima kasih kepada pengerusi dan ahli panel.", zh: "感谢主席和各位评审老师。", note: "正式答辩开场。" },
  { id: "p023", day: 9, category: "opening", ms: "Hari ini saya akan membentangkan kajian saya bertajuk ___.", zh: "今天我将汇报题为___的研究。", note: "答辩必背句。" },
  { id: "p024", day: 9, category: "opening", ms: "Pembentangan saya akan mengambil masa kira-kira sepuluh minit.", zh: "我的汇报大约需要十分钟。", note: "根据实际时间替换数字。" },
  { id: "p025", day: 10, category: "structure", ms: "Pembentangan ini mempunyai empat bahagian.", zh: "本次汇报有四个部分。", note: "引出结构。" },
  { id: "p026", day: 10, category: "structure", ms: "Pertama, saya akan menerangkan latar belakang kajian.", zh: "第一，我会说明研究背景。", note: "结构词：Pertama 第一。" },
  { id: "p027", day: 11, category: "structure", ms: "Kedua, saya akan menjelaskan metodologi kajian.", zh: "第二，我会解释研究方法。", note: "metodologi是学术语境常用词。" },
  { id: "p028", day: 11, category: "structure", ms: "Ketiga, saya akan membincangkan dapatan utama.", zh: "第三，我会讨论主要发现。", note: "dapatan = findings。" },
  { id: "p029", day: 12, category: "structure", ms: "Akhir sekali, saya akan membuat kesimpulan.", zh: "最后，我会作出结论。", note: "收束结构。" },
  { id: "p030", day: 12, category: "research", ms: "Kajian ini bertujuan untuk ___.", zh: "本研究旨在___。", note: "目的句核心模板。" },
  { id: "p031", day: 13, category: "research", ms: "Isu utama dalam kajian ini ialah ___.", zh: "本研究的主要问题是___。", note: "说明研究问题。" },
  { id: "p032", day: 13, category: "research", ms: "Persoalan kajian utama ialah ___.", zh: "主要研究问题是___。", note: "比 soalan 更学术。" },
  { id: "p033", day: 14, category: "research", ms: "Objektif pertama kajian ini adalah untuk ___.", zh: "本研究的第一个目标是___。", note: "列研究目标。" },
  { id: "p034", day: 14, category: "research", ms: "Objektif kedua adalah untuk ___.", zh: "第二个目标是___。", note: "配合上一句。" },
  { id: "p035", day: 15, category: "research", ms: "Kajian ini menggunakan pendekatan kualitatif.", zh: "本研究采用质性方法。", note: "如是量化，换成 kuantitatif。" },
  { id: "p036", day: 15, category: "research", ms: "Kajian ini menggunakan pendekatan kuantitatif.", zh: "本研究采用量化方法。", note: "二选一背熟。" },
  { id: "p037", day: 16, category: "research", ms: "Data dikumpulkan melalui soal selidik.", zh: "数据通过问卷收集。", note: "问卷研究常用。" },
  { id: "p038", day: 16, category: "research", ms: "Data dikumpulkan melalui temu bual.", zh: "数据通过访谈收集。", note: "访谈研究常用。" },
  { id: "p039", day: 17, category: "research", ms: "Sampel kajian terdiri daripada ___.", zh: "研究样本包括___。", note: "介绍对象。" },
  { id: "p040", day: 17, category: "research", ms: "Analisis data dijalankan menggunakan ___.", zh: "数据分析使用___进行。", note: "可填SPSS、NVivo、thematic analysis等。" },
  { id: "p041", day: 18, category: "research", ms: "Dapatan menunjukkan bahawa ___.", zh: "研究发现显示___。", note: "结果陈述模板。" },
  { id: "p042", day: 18, category: "research", ms: "Keputusan ini menunjukkan bahawa ___.", zh: "该结果表明___。", note: "结果解释模板。" },
  { id: "p043", day: 19, category: "research", ms: "Secara keseluruhan, dapatan ini menyokong ___.", zh: "总体而言，这些发现支持___。", note: "总结发现。" },
  { id: "p044", day: 19, category: "research", ms: "Namun begitu, terdapat beberapa batasan.", zh: "然而，仍存在一些限制。", note: "承认局限。" },
  { id: "p045", day: 20, category: "research", ms: "Batasan pertama ialah saiz sampel yang terhad.", zh: "第一个限制是样本量有限。", note: "常见局限句。" },
  { id: "p046", day: 20, category: "research", ms: "Kajian masa depan boleh melibatkan sampel yang lebih besar.", zh: "未来研究可以纳入更大的样本。", note: "局限后的建议。" },
  { id: "p047", day: 21, category: "research", ms: "Sumbangan kajian ini ialah ___.", zh: "本研究的贡献是___。", note: "答辩常被问。" },
  { id: "p048", day: 21, category: "research", ms: "Kajian ini penting kerana ___.", zh: "本研究重要，因为___。", note: "意义句。" },
  { id: "p049", day: 22, category: "qa", ms: "Terima kasih atas soalan tersebut.", zh: "谢谢这个问题。", note: "答题前的万能缓冲。" },
  { id: "p050", day: 22, category: "qa", ms: "Jika saya faham dengan betul, Prof. bertanya tentang ___.", zh: "如果我理解正确，教授问的是___。", note: "确认问题，非常实用。" },
  { id: "p051", day: 23, category: "qa", ms: "Saya akan jawab soalan ini dalam dua bahagian.", zh: "我会分两部分回答这个问题。", note: "给回答搭结构。" },
  { id: "p052", day: 23, category: "qa", ms: "Bahagian pertama berkaitan dengan metodologi.", zh: "第一部分与研究方法有关。", note: "可换成 dapatan, teori, sampel。" },
  { id: "p053", day: 24, category: "qa", ms: "Berdasarkan data yang saya kumpulkan, ___.", zh: "根据我收集的数据，___。", note: "让回答回到证据。" },
  { id: "p054", day: 24, category: "qa", ms: "Berdasarkan literatur, ___.", zh: "根据文献，___。", note: "回到文献支持。" },
  { id: "p055", day: 25, category: "qa", ms: "Pada pendapat saya, perkara ini boleh dijelaskan melalui ___.", zh: "我认为，这一点可以通过___解释。", note: "表达观点。" },
  { id: "p056", day: 25, category: "qa", ms: "Perkara itu berada di luar skop kajian saya.", zh: "这一点超出了我的研究范围。", note: "礼貌处理超范围问题。" },
  { id: "p057", day: 26, category: "qa", ms: "Saya akui perkara itu merupakan batasan kajian ini.", zh: "我承认这是本研究的一个限制。", note: "坦诚且专业。" },
  { id: "p058", day: 26, category: "qa", ms: "Cadangan Prof. sangat membantu untuk penambahbaikan kajian ini.", zh: "教授的建议对改进本研究很有帮助。", note: "回应批评时很好用。" },
  { id: "p059", day: 27, category: "qa", ms: "Saya belum meneliti aspek itu secara mendalam.", zh: "我还没有深入研究这个方面。", note: "不要硬编答案。" },
  { id: "p060", day: 27, category: "qa", ms: "Namun, saya akan pertimbangkan perkara ini dalam kajian akan datang.", zh: "不过，我会在未来研究中考虑这一点。", note: "把问题转为未来方向。" },
  { id: "p061", day: 28, category: "closing", ms: "Sekian pembentangan saya. Terima kasih.", zh: "我的汇报到此结束。谢谢。", note: "最稳的结束语。" },
  { id: "p062", day: 28, category: "closing", ms: "Saya sedia menerima soalan daripada ahli panel.", zh: "我准备接受评审老师的提问。", note: "进入问答环节。" },
  { id: "p063", day: 29, category: "closing", ms: "Terima kasih atas masa dan perhatian semua.", zh: "感谢大家的时间和聆听。", note: "礼貌收尾。" },
  { id: "p064", day: 29, category: "closing", ms: "Saya menghargai komen dan cadangan daripada ahli panel.", zh: "我感谢评审老师们的评论和建议。", note: "答辩结束可用。" },
  { id: "p065", day: 30, category: "polite", ms: "Boleh saya ambil sedikit masa untuk berfikir?", zh: "我可以花一点时间思考吗？", note: "被问住时先稳住。" },
  { id: "p066", day: 30, category: "polite", ms: "Maaf, boleh saya semak semula nota saya?", zh: "抱歉，我可以再看一下我的笔记吗？", note: "适合线上或线下答辩。" },
  { id: "p067", day: 31, category: "vocab", ms: "latar belakang kajian", zh: "研究背景", note: "background of the study" },
  { id: "p068", day: 31, category: "vocab", ms: "pernyataan masalah", zh: "问题陈述", note: "problem statement" },
  { id: "p069", day: 32, category: "vocab", ms: "objektif kajian", zh: "研究目标", note: "research objectives" },
  { id: "p070", day: 32, category: "vocab", ms: "persoalan kajian", zh: "研究问题", note: "research questions" },
  { id: "p071", day: 33, category: "vocab", ms: "sorotan literatur", zh: "文献综述", note: "literature review" },
  { id: "p072", day: 33, category: "vocab", ms: "kerangka teori", zh: "理论框架", note: "theoretical framework" },
  { id: "p073", day: 34, category: "vocab", ms: "kaedah kajian", zh: "研究方法", note: "research method" },
  { id: "p074", day: 34, category: "vocab", ms: "instrumen kajian", zh: "研究工具", note: "research instrument" },
  { id: "p075", day: 35, category: "vocab", ms: "dapatan kajian", zh: "研究发现", note: "research findings" },
  { id: "p076", day: 35, category: "vocab", ms: "perbincangan", zh: "讨论", note: "discussion" },
  { id: "p077", day: 36, category: "vocab", ms: "kesimpulan", zh: "结论", note: "conclusion" },
  { id: "p078", day: 36, category: "vocab", ms: "cadangan kajian masa depan", zh: "未来研究建议", note: "recommendations for future research" },
  { id: "p079", day: 37, category: "qa", ms: "Soalan ini sangat penting untuk kajian saya.", zh: "这个问题对我的研究非常重要。", note: "适合先肯定问题价值。" },
  { id: "p080", day: 37, category: "qa", ms: "Saya akan jelaskan dengan merujuk kepada slaid ini.", zh: "我会参考这张幻灯片来说明。", note: "把回答带回PPT。" },
  { id: "p081", day: 38, category: "meeting", ms: "Saya telah mengemas kini slaid pembentangan.", zh: "我已经更新了答辩幻灯片。", note: "跟导师沟通PPT版本。" },
  { id: "p082", day: 38, category: "meeting", ms: "Boleh Prof. semak bahagian kesimpulan?", zh: "教授可以看一下结论部分吗？", note: "请求具体反馈。" },
  { id: "p083", day: 39, category: "opening", ms: "Sebelum saya mula, izinkan saya memperkenalkan diri secara ringkas.", zh: "开始之前，请允许我简短介绍自己。", note: "较正式开场。" },
  { id: "p084", day: 39, category: "research", ms: "Topik ini dipilih kerana ia berkaitan rapat dengan ___.", zh: "选择这个主题是因为它与___密切相关。", note: "选题理由。" },
  { id: "p085", day: 40, category: "qa", ms: "Perbezaan utama kajian saya dengan kajian terdahulu ialah ___.", zh: "我的研究与既有研究的主要区别是___。", note: "回答创新点。" },
  { id: "p086", day: 40, category: "research", ms: "Implikasi praktikal kajian ini ialah ___.", zh: "本研究的实践启示是___。", note: "教育或管理类答辩常用。" },
  { id: "p087", day: 1, category: "daily", ms: "Selamat tengah hari, Dr.", zh: "老师，中午好。", note: "中午或午后见面时使用。" },
  { id: "p088", day: 1, category: "daily", ms: "Selamat petang, Prof.", zh: "教授，下午好。", note: "下午见面时使用。" },
  { id: "p089", day: 1, category: "daily", ms: "Sudah makan, Dr.?", zh: "老师，吃过了吗？", note: "马来西亚日常small talk常见句。" },
  { id: "p090", day: 2, category: "daily", ms: "Saya baru sampai.", zh: "我刚到。", note: "到办公室、会议室或答辩地点时可用。" },
  { id: "p091", day: 2, category: "daily", ms: "Cuaca hari ini agak panas.", zh: "今天天气有点热。", note: "简单安全的寒暄话题。" },
  { id: "p092", day: 2, category: "daily", ms: "Saya tunggu di luar bilik.", zh: "我在房间外面等。", note: "答辩前等候时可用。" },
  { id: "p093", day: 3, category: "daily", ms: "Boleh saya duduk di sini?", zh: "我可以坐这里吗？", note: "进办公室或会议室前使用。" },
  { id: "p094", day: 3, category: "daily", ms: "Maaf, saya agak gementar hari ini.", zh: "不好意思，我今天有点紧张。", note: "答辩前自然表达情绪。" },
  { id: "p095", day: 3, category: "daily", ms: "Semoga semuanya berjalan lancar.", zh: "希望一切顺利。", note: "考试、答辩、会议前都可用。" },
  { id: "p096", day: 4, category: "meeting", ms: "Boleh saya masuk sekarang?", zh: "我现在可以进去吗？", note: "进入办公室或答辩室前使用。" },
  { id: "p097", day: 4, category: "meeting", ms: "Saya akan menunggu arahan daripada pengerusi.", zh: "我会等待主席的指示。", note: "正式答辩前非常实用。" },
  { id: "p098", day: 4, category: "meeting", ms: "Adakah semua ahli panel sudah hadir?", zh: "所有评审老师都已经到场了吗？", note: "适合低声向工作人员或导师确认。" },
  { id: "p099", day: 5, category: "opening", ms: "Boleh saya mulakan pembentangan sekarang?", zh: "我现在可以开始汇报吗？", note: "正式开始前的关键句。" },
  { id: "p100", day: 5, category: "opening", ms: "Adakah slaid saya dapat dilihat dengan jelas?", zh: "我的幻灯片能看清楚吗？", note: "线上或投影时使用。" },
  { id: "p101", day: 5, category: "opening", ms: "Boleh saya kongsi skrin sekarang?", zh: "我现在可以共享屏幕吗？", note: "线上答辩前使用。" },
  { id: "p102", day: 6, category: "polite", ms: "Suara saya jelas?", zh: "我的声音清楚吗？", note: "线上或麦克风场景使用。" },
  { id: "p103", day: 6, category: "polite", ms: "Jika ada masalah teknikal, sila beritahu saya.", zh: "如果有技术问题，请告诉我。", note: "线上答辩很实用。" },
  { id: "p104", day: 7, category: "meeting", ms: "Terima kasih kerana hadir hari ini.", zh: "感谢您今天出席。", note: "答辩前后都可以表达礼貌。" },
  { id: "p105", day: 7, category: "meeting", ms: "Saya hargai masa Prof. dan ahli panel.", zh: "我感谢教授和各位评审老师的时间。", note: "比简单谢谢更正式。" },
];
