const baseVocabulary = [
  { ms: "selamat", zh: "平安的；祝愿用语", en: "safe; greeting word", type: "adjective" },
  { ms: "pagi", zh: "早上", en: "morning", type: "noun" },
  { ms: "profesor", zh: "教授", en: "professor", type: "noun", aliases: ["prof"] },
  { ms: "dr", zh: "博士；老师称呼", en: "doctor; academic title", type: "title" },
  { ms: "apa", zh: "什么", en: "what", type: "question word" },
  { ms: "khabar", zh: "消息；近况", en: "news; condition", type: "noun" },
  { ms: "tengah hari", zh: "中午", en: "noon; midday", type: "noun phrase" },
  { ms: "petang", zh: "下午；傍晚", en: "afternoon; evening", type: "noun" },
  { ms: "sudah", zh: "已经", en: "already", type: "aspect marker" },
  { ms: "makan", zh: "吃；吃饭", en: "to eat", type: "verb" },
  { ms: "saya", zh: "我", en: "I; me", type: "pronoun" },
  { ms: "baik", zh: "好；良好", en: "good; well", type: "adjective" },
  { ms: "terima kasih", zh: "谢谢", en: "thank you", type: "expression" },
  { ms: "nama", zh: "名字", en: "name", type: "noun" },
  { ms: "ialah", zh: "是", en: "is; namely", type: "linking verb" },
  { ms: "pelajar", zh: "学生", en: "student", type: "noun" },
  { ms: "tahun akhir", zh: "最后一年", en: "final year", type: "phrase" },
  { ms: "baru", zh: "刚刚；新的", en: "just; new", type: "adverb" },
  { ms: "sampai", zh: "到达", en: "to arrive", type: "verb" },
  { ms: "cuaca", zh: "天气", en: "weather", type: "noun" },
  { ms: "agak", zh: "有点；相当", en: "rather; quite", type: "adverb" },
  { ms: "panas", zh: "热的", en: "hot", type: "adjective" },
  { ms: "sedang", zh: "正在", en: "currently; in progress", type: "aspect marker" },
  { ms: "belajar", zh: "学习", en: "to learn; to study", type: "verb" },
  { ms: "bahasa Melayu", zh: "马来语", en: "Malay language", type: "noun phrase" },
  { ms: "maaf", zh: "抱歉；不好意思", en: "sorry; excuse me", type: "expression" },
  { ms: "masih", zh: "仍然；还", en: "still", type: "adverb" },
  { ms: "terhad", zh: "有限的", en: "limited", type: "adjective" },
  { ms: "boleh", zh: "可以；能够", en: "can; may", type: "modal verb" },
  { ms: "cuba", zh: "尝试", en: "to try", type: "verb" },
  { ms: "jawab", zh: "回答", en: "to answer", type: "verb" },
  { ms: "dalam", zh: "用；在……里面", en: "in; using", type: "preposition" },
  { ms: "di", zh: "在", en: "at; in", type: "preposition" },
  { ms: "luar", zh: "外面", en: "outside", type: "noun/adverb" },
  { ms: "bilik", zh: "房间", en: "room", type: "noun" },
  { ms: "duduk", zh: "坐", en: "to sit", type: "verb" },
  { ms: "sini", zh: "这里", en: "here", type: "place word" },
  { ms: "dahulu", zh: "先；之前", en: "first; before", type: "adverb" },
  { ms: "jika", zh: "如果", en: "if", type: "conjunction" },
  { ms: "perlu", zh: "需要", en: "need; necessary", type: "modal verb" },
  { ms: "akan", zh: "将会", en: "will", type: "future marker" },
  { ms: "ulang", zh: "重复", en: "to repeat", type: "verb" },
  { ms: "sekali lagi", zh: "再一次", en: "one more time", type: "phrase" },
  { ms: "bercakap", zh: "说话", en: "to speak", type: "verb" },
  { ms: "sedikit", zh: "一点；稍微", en: "a little", type: "adverb" },
  { ms: "perlahan", zh: "慢地；慢的", en: "slowly; slow", type: "adverb" },
  { ms: "kurang", zh: "不太；较少", en: "less; not very", type: "adverb" },
  { ms: "faham", zh: "明白", en: "to understand", type: "verb" },
  { ms: "bahagian", zh: "部分", en: "part; section", type: "noun" },
  { ms: "terakhir", zh: "最后的", en: "last; final", type: "adjective" },
  { ms: "gementar", zh: "紧张的", en: "nervous", type: "adjective" },
  { ms: "semoga", zh: "希望；愿", en: "hopefully; may", type: "expression" },
  { ms: "semuanya", zh: "一切；所有事情", en: "everything", type: "pronoun" },
  { ms: "berjalan lancar", zh: "顺利进行", en: "to go smoothly", type: "phrase" },
  { ms: "ingin", zh: "想要", en: "would like to", type: "verb" },
  { ms: "bertanya", zh: "询问", en: "to ask", type: "verb" },
  { ms: "tentang", zh: "关于", en: "about", type: "preposition" },
  { ms: "draf", zh: "草稿", en: "draft", type: "noun" },
  { ms: "temu janji", zh: "预约；会面", en: "appointment", type: "noun phrase" },
  { ms: "minggu", zh: "星期；周", en: "week", type: "noun" },
  { ms: "ini", zh: "这；这个", en: "this", type: "determiner" },
  { ms: "adakah", zh: "是否；是不是", en: "whether; is it", type: "question marker" },
  { ms: "lapang", zh: "有空的", en: "free; available", type: "adjective" },
  { ms: "hari", zh: "天；日", en: "day", type: "noun" },
  { ms: "masuk", zh: "进去；进入", en: "to enter", type: "verb" },
  { ms: "sekarang", zh: "现在", en: "now", type: "adverb" },
  { ms: "telah", zh: "已经", en: "already; has", type: "past marker" },
  { ms: "menghantar", zh: "发送；提交", en: "to send; to submit", type: "verb" },
  { ms: "fail", zh: "文件", en: "file", type: "noun" },
  { ms: "melalui", zh: "通过", en: "through; via", type: "preposition" },
  { ms: "sahkan", zh: "确认", en: "to confirm", type: "verb" },
  { ms: "masa", zh: "时间", en: "time", type: "noun" },
  { ms: "pertemuan", zh: "会面", en: "meeting", type: "noun" },
  { ms: "bimbingan", zh: "指导", en: "guidance", type: "noun" },
  { ms: "menunggu", zh: "等待", en: "to wait", type: "verb" },
  { ms: "arahan", zh: "指示", en: "instruction", type: "noun" },
  { ms: "daripada", zh: "来自；从", en: "from; than", type: "preposition" },
  { ms: "hadir", zh: "出席；到场", en: "to attend; present", type: "verb" },
  { ms: "membuat", zh: "做；进行", en: "to do; to make", type: "verb" },
  { ms: "pembetulan", zh: "修改；纠正", en: "correction", type: "noun" },
  { ms: "secepat mungkin", zh: "尽快", en: "as soon as possible", type: "phrase" },
  { ms: "maklum balas", zh: "反馈", en: "feedback", type: "noun phrase" },
  { ms: "assalamualaikum", zh: "愿你平安", en: "peace be upon you", type: "greeting" },
  { ms: "semua", zh: "所有人；大家", en: "all; everyone", type: "pronoun" },
  { ms: "kepada", zh: "给；向", en: "to", type: "preposition" },
  { ms: "pengerusi", zh: "主席", en: "chairperson", type: "noun" },
  { ms: "dan", zh: "和", en: "and", type: "conjunction" },
  { ms: "ahli panel", zh: "评审老师；小组成员", en: "panel member", type: "noun phrase" },
  { ms: "membentangkan", zh: "汇报；展示", en: "to present", type: "verb" },
  { ms: "mulakan", zh: "开始", en: "to start; begin", type: "verb" },
  { ms: "kajian", zh: "研究", en: "study; research", type: "noun" },
  { ms: "bertajuk", zh: "题为", en: "entitled", type: "verb" },
  { ms: "pembentangan", zh: "汇报；展示", en: "presentation", type: "noun" },
  { ms: "mengambil masa", zh: "花费时间", en: "to take time", type: "phrase" },
  { ms: "kira-kira", zh: "大约", en: "approximately", type: "adverb" },
  { ms: "minit", zh: "分钟", en: "minute", type: "noun" },
  { ms: "slaid", zh: "幻灯片", en: "slide", type: "noun" },
  { ms: "dapat", zh: "能够；可以", en: "can; able to", type: "modal verb" },
  { ms: "dilihat", zh: "被看见", en: "seen; visible", type: "passive verb" },
  { ms: "jelas", zh: "清楚的", en: "clear", type: "adjective" },
  { ms: "kongsi", zh: "分享", en: "to share", type: "verb" },
  { ms: "skrin", zh: "屏幕", en: "screen", type: "noun" },
  { ms: "suara", zh: "声音", en: "voice", type: "noun" },
  { ms: "ada", zh: "有；存在", en: "there is; have", type: "verb" },
  { ms: "masalah teknikal", zh: "技术问题", en: "technical problem", type: "noun phrase" },
  { ms: "sila", zh: "请", en: "please", type: "polite marker" },
  { ms: "beritahu", zh: "告诉", en: "to inform; tell", type: "verb" },
  { ms: "hargai", zh: "珍惜；感谢", en: "to appreciate", type: "verb" },
  { ms: "mempunyai", zh: "有；拥有", en: "to have", type: "verb" },
  { ms: "empat", zh: "四", en: "four", type: "number" },
  { ms: "pertama", zh: "第一", en: "first", type: "sequence" },
  { ms: "kedua", zh: "第二", en: "second", type: "sequence" },
  { ms: "ketiga", zh: "第三", en: "third", type: "sequence" },
  { ms: "akhir sekali", zh: "最后", en: "lastly", type: "connector" },
  { ms: "menerangkan", zh: "说明；解释", en: "to explain", type: "verb" },
  { ms: "menjelaskan", zh: "解释；阐明", en: "to clarify; to explain", type: "verb" },
  { ms: "metodologi", zh: "方法论；研究方法", en: "methodology", type: "noun" },
  { ms: "membincangkan", zh: "讨论", en: "to discuss", type: "verb" },
  { ms: "dapatan", zh: "发现；研究结果", en: "findings", type: "noun" },
  { ms: "utama", zh: "主要的", en: "main", type: "adjective" },
  { ms: "kesimpulan", zh: "结论", en: "conclusion", type: "noun" },
  { ms: "bertujuan", zh: "旨在", en: "aims; intends", type: "verb" },
  { ms: "untuk", zh: "为了；以便", en: "to; in order to", type: "preposition" },
  { ms: "isu", zh: "议题；问题", en: "issue", type: "noun" },
  { ms: "persoalan", zh: "问题；研究问题", en: "question; issue", type: "noun" },
  { ms: "objektif", zh: "目标", en: "objective", type: "noun" },
  { ms: "menggunakan", zh: "使用；采用", en: "to use", type: "verb" },
  { ms: "pendekatan", zh: "方法；取向", en: "approach", type: "noun" },
  { ms: "kualitatif", zh: "质性的", en: "qualitative", type: "adjective" },
  { ms: "kuantitatif", zh: "量化的", en: "quantitative", type: "adjective" },
  { ms: "data", zh: "数据", en: "data", type: "noun" },
  { ms: "dikumpulkan", zh: "被收集", en: "collected", type: "passive verb" },
  { ms: "soal selidik", zh: "问卷", en: "questionnaire", type: "noun phrase" },
  { ms: "temu bual", zh: "访谈", en: "interview", type: "noun phrase" },
  { ms: "sampel", zh: "样本", en: "sample", type: "noun" },
  { ms: "terdiri daripada", zh: "由……组成", en: "consists of", type: "phrase" },
  { ms: "analisis", zh: "分析", en: "analysis", type: "noun" },
  { ms: "dijalankan", zh: "被进行", en: "conducted; carried out", type: "passive verb" },
  { ms: "menunjukkan", zh: "显示；表明", en: "to show; indicate", type: "verb" },
  { ms: "bahawa", zh: "……这一点；that", en: "that", type: "connector" },
  { ms: "keputusan", zh: "结果", en: "result", type: "noun" },
  { ms: "secara keseluruhan", zh: "总体而言", en: "overall", type: "phrase" },
  { ms: "menyokong", zh: "支持", en: "to support", type: "verb" },
  { ms: "batasan", zh: "限制；局限", en: "limitation", type: "noun" },
  { ms: "saiz sampel", zh: "样本量", en: "sample size", type: "noun phrase" },
  { ms: "kajian masa depan", zh: "未来研究", en: "future research", type: "noun phrase" },
  { ms: "sumbangan", zh: "贡献", en: "contribution", type: "noun" },
  { ms: "penting", zh: "重要的", en: "important", type: "adjective" },
  { ms: "soalan", zh: "问题", en: "question", type: "noun" },
  { ms: "skop", zh: "范围", en: "scope", type: "noun" },
  { ms: "cadangan", zh: "建议", en: "suggestion; recommendation", type: "noun" },
  { ms: "penambahbaikan", zh: "改进", en: "improvement", type: "noun" },
  { ms: "implikasi praktikal", zh: "实践启示", en: "practical implication", type: "noun phrase" },
];
